import { jsPDF } from 'jspdf'

export function exportSessionPDF(session) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 40
  const maxWidth = pageWidth - margin * 2
  let y = 50

  function addText(text, size, bold, color) {
    doc.setFontSize(size)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    if (color) doc.setTextColor(...color)
    else doc.setTextColor(27, 42, 107)
    const lines = doc.splitTextToSize(text, maxWidth)
    lines.forEach(line => {
      if (y > 780) { doc.addPage(); y = 50 }
      doc.text(line, margin, y)
      y += size * 1.4
    })
    y += 4
  }

  function divider() {
    if (y > 780) { doc.addPage(); y = 50 }
    doc.setDrawColor(200, 200, 220)
    doc.line(margin, y, pageWidth - margin, y)
    y += 12
  }

  addText('HearAssist Session Notes', 22, true, [27, 42, 107])
  addText(`${session.title || 'Untitled Session'}`, 16, true, [123, 94, 167])
  addText(`Mode: ${session.mode === 'lecture' ? 'Lecture' : 'Conversation'} | Date: ${session.date} | Duration: ${session.duration}`, 10, false, [100, 100, 120])
  divider()

  if (session.notes) {
    addText('Lecture Overview', 14, true, [27, 42, 107])
    addText(session.notes.overview || '', 11, false, [60, 60, 80])
    y += 8

    addText('Key Points', 14, true, [27, 42, 107])
    ;(session.notes.keyPoints || []).forEach(kp => {
      addText(`• ${kp}`, 11, false, [60, 60, 80])
    })
    y += 8

    addText('Keywords', 14, true, [27, 42, 107])
    addText((session.notes.keywords || []).join(', '), 11, false, [60, 60, 80])
    divider()
  }

  addText('Full Transcript', 14, true, [27, 42, 107])
  ;(session.transcript || []).forEach(entry => {
    addText(`Speaker ${entry.speaker} [${entry.timestamp}]:`, 10, true, [80, 80, 120])
    addText(entry.text, 11, false, [60, 60, 80])
    y += 2
  })

  divider()
  addText(`Generated by HearAssist | ${new Date().toLocaleDateString()}`, 9, false, [150, 150, 170])

  doc.save(`hearassist-${(session.title || 'session').replace(/\s+/g, '-').toLowerCase()}.pdf`)
}

export function exportNotesPDF(session) {
  exportSessionPDF(session)
}
